[project]
name = "habit-tracker"
version = "0.1.0"
description = "Backend API for Habit Tracker"
requires-python = ">=3.10"

dependencies = [
  "fastapi",
  "uvicorn>=0.35.0",
  "sqlalchemy",
  "psycopg2-binary",
  "pydantic-settings",
  "python-dotenv"
]

[dependency-groups]
dev = []
